doctrine:
    orm:
        resolve_target_entities:
            Harmony\Bundle\CoreBundle\Model\Config: App\Entity\Config
            Harmony\Bundle\CoreBundle\Model\Extension: App\Entity\Extension
            Harmony\Bundle\CoreBundle\Model\Parameter: App\Entity\Parameter