doctrine_mongodb:
    resolve_target_documents:
        Harmony\Bundle\CoreBundle\Model\ConfigInterface: App\Document\Config
        Harmony\Bundle\CoreBundle\Model\ExtensionInterface: App\Document\Extension
        Harmony\Bundle\CoreBundle\Model\ParameterInterface: App\Document\Parameter