doctrine:
    orm:
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: App\Entity\User
            Harmony\Bundle\UserBundle\Group\GroupInterface: App\Entity\Group