doctrine_mongodb:
    resolve_target_documents:
        Symfony\Component\Security\Core\User\UserInterface: App\Document\User
        Harmony\Bundle\UserBundle\Group\GroupInterface: App\Document\Group