harmony_translation_manager:
    fallback_locale: [en]         # (required) default locale(s) to use
    managed_locales: [en, fr, de] # (required) locales that the bundle has to manage

doctrine:
    orm:
        resolve_target_entities:
            Harmony\Extension\TranslationManager\Manager\FileInterface: App\Entity\TranslationManagerFile
            Harmony\Extension\TranslationManager\Manager\TranslationInterface: App\Entity\TranslationManagerTranslation
            Harmony\Extension\TranslationManager\Manager\TransUnitInterface: App\Entity\TranslationManagerTransUnit