harmony_translation_manager:
    fallback_locale: [en]         # (required) default locale(s) to use
    managed_locales: [en, fr, de] # (required) locales that the bundle has to manage

doctrine_mongodb:
    resolve_target_documents:
        Harmony\Extension\TranslationManager\Manager\FileInterface: App\Document\TranslationManagerFile
        Harmony\Extension\TranslationManager\Manager\TranslationInterface: App\Document\TranslationManagerTranslation
        Harmony\Extension\TranslationManager\Manager\TransUnitInterface: App\Document\TranslationManagerTransUnit