doctrine_mongodb:
    resolve_target_documents:
        Symfony\Cmf\Component\Routing\RedirectRouteInterface: App\Document\RedirectRoute
        Symfony\Cmf\Component\Routing\RouteObjectInterface: App\Document\Route

harmony_routing:
    chain:
        routers_by_id:
            Harmony\Bundle\RoutingBundle\Routing\DynamicRouter: 20
            router.default: 100
    dynamic:
        persistence:
            mongodb:
                enabled: true