doctrine_mongodb:
    resolve_target_documents:
        Symfony\Cmf\Component\Routing\RedirectRouteInterface: App\Document\RedirectRoute
        Symfony\Cmf\Component\Routing\RouteObjectInterface: App\Document\Route

harmony_routing:
    dynamic:
        enabled: true