doctrine:
    orm:
        resolve_target_entities:
            Symfony\Cmf\Component\Routing\RedirectRouteInterface: App\Entity\RedirectRoute
            Symfony\Cmf\Component\Routing\RouteObjectInterface: App\Entity\Route

harmony_routing:
    dynamic:
        enabled: true