doctrine_mongodb:
    resolve_target_documents:
        Harmony\Bundle\RoutingBundle\Model\Route: App\Document\Route
        Harmony\Bundle\RoutingBundle\Model\RedirectRoute: App\Document\RedirectRoute

harmony_routing:
    chain:
        routers_by_id:
            harmony_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        persistence:
            mongodb:
                enabled: true