doctrine:
    orm:
        resolve_target_entities:
            Harmony\Bundle\RoutingBundle\Model\Route: App\Entity\Route
            Harmony\Bundle\RoutingBundle\Model\RedirectRoute: App\Entity\RedirectRoute

harmony_routing:
    chain:
        routers_by_id:
            harmony_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        persistence:
            orm:
                enabled: true